#!/bin/bash

USER_BIN_DIR="$HOME/.usr/local/bin"
SCRIPT_DIR="$(dirname $(readlink -f ${BASH_SOURCE[0]}))"

# Initializing
if [[ ! -d "$USER_BIN_DIR" ]]; then
  sudo pacman-key --init
  sudo pacman-key --populate archlinux
  sudo pacman-key --populate holo
  mkdir -p $USER_BIN_DIR
  echo "[INFO]: '$USER_BIN_DIR' directory created"
  ln -s $SCRIPT_DIR/setup $USER_BIN_DIR/setup
  echo "[INFO]: Setup script symlink created"

  echo "[INFO]: Setting up aliases"
  echo "" >> ~/.bashrc
  echo "alias vi=\"vim\"" >> ~/.bashrc
  echo "alias ll=\"ls -la\"" >> ~/.bashrc
  echo "[INFO]: Aliases configured"

  echo "export PATH=\"\$PATH:$USER_BIN_DIR\"" >> ~/.bash_profile
  . ~/.bash_profile
  echo "[INFO]: Bash profile updated"
fi

# Pre Setup
sudo steamos-readonly disable

# Install Packages
if $(pacman-key --list-keys > /dev/null 2>&1); [ "$?" -ne 0 ]; then
  echo "[INFO]: Pacman key not initialized. Initializing..."
  sudo pacman-key --init
  sudo pacman-key --populate archlinux holo
fi

#sudo pacman -Sy --noconfirm --needed --overwrite \* mc networkmanager-l2tp strongswan samba
sudo pacman -Sy --noconfirm --needed mc networkmanager-l2tp strongswan

# Configure Samba
. $SCRIPT_DIR/samba/samba.sh

# Post Setup
sudo steamos-readonly enable

