#!/bin/bash

set -e

USER_BIN_DIR="$HOME/.usr/local/bin"

# Initializing
if [[ ! -d "$USER_BIN_DIR" ]]; then
  mkdir -p $USER_BIN_DIR
  echo "[INFO]: $USER_BIN_DIR created"
  ln -s setup $USER_BIN_DIR/setup
fi

# Pre Setup
sudo steamos-readonly disable

# Install Packages
#sudo pacman -Sy --noconfirm --needed --overwrite \* mc networkmanager-l2tp strongswan samba
sudo pacman -Sy --noconfirm --needed mc networkmanager-l2tp strongswan samba

# Configure Samba
. ../samba.sh

# Post Setup
sudo steamos-readonly enable
